### ISSUE TITLE
Source Code Usage Request

### ISSUE THREAD

**Issue by mathsy** [lithander/MinimalChessEngine#2]
Dear Developer,

I'd like to use parts of your engine's source code for my own engine. I plan to redistribute the changed code on github, of course I'll credit you and your repository.
My question is if this is okay for you... 

Thanks in advantage

**Comment by lithander** [comment]
Hi mathsy!

MinimalChessEngine is open-source under the simple and very permissive [MIT License](https://github.com/lithander/MinimalChessEngine/blob/master/LICENSE). 

Unlike other licenses (like Stockfish's GPL for example) using my source doesn't force you to make your own engine open source, too. 

The only requirement is indeed to give proper credits. So if you link to the github repository and maybe additionally mention that the original source is published under the MIT license that would be entirely fine!
